#!/usr/bin/python

import time

#mrmr 10
#InfoGain	10 30 50
#ReliefF	10 17 50

#ChiSquared	10 17 30 50
#GainRatio	10 17 30 50
#PCA	    10 17 30 50
#SVM        10 17 30 50

#feature:
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphFSRun CFSubsetEval

#recommendation1:
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun given_5 CFSubsetEval &
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun given_10 CFSubsetEval &
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun given_20 CFSubsetEval

#recommendation: recommendation1
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun given_30 CFSubsetEval &
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun given_50 CFSubsetEval &
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun given_all CFSubsetEval

#evaluation:
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphEvalRun given_5 PageRank 5
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphEvalRun given_10 PageRank 5 
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphEvalRun given_20 PageRank 5 
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphEvalRun given_30 PageRank 5 
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphEvalRun given_50 PageRank 5 
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphEvalRun given_all PageRank 5 

#featureCF:
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphFSRun RankerWeka 11 LatentSemanticAnalysis

#recommendationCF:
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun given_5 RankerWeka 11 LatentSemanticAnalysis &
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun given_10 RankerWeka 11 LatentSemanticAnalysis &
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun given_20 RankerWeka 11 LatentSemanticAnalysis &
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun given_30 RankerWeka 11 LatentSemanticAnalysis &
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun given_50 RankerWeka 11 LatentSemanticAnalysis &
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun given_all RankerWeka 11 LatentSemanticAnalysis

#evaluationCF:
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphEvalRun given_5 RankerWeka 11 LatentSemanticAnalysis
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphEvalRun given_10 RankerWeka 11 LatentSemanticAnalysis
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphEvalRun given_20 RankerWeka 11 LatentSemanticAnalysis
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphEvalRun given_30 RankerWeka 11 LatentSemanticAnalysis
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphEvalRun given_50 RankerWeka 11 LatentSemanticAnalysis
#	java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphEvalRun given_all RankerWeka 11 LatentSemanticAnalysis

allalg=["ChiSquared","GainRatio","PCA","SVM"]
topN=["10" ,"17", "30", "50"]
givenN=["given_5","given_10","given_20","given_30","given_50","given_all"]
for alg in allalg:
    for top in topN:
        print "\nFS \n"
#       cmd = "java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphFSRun RankerWeka 11 LatentSemanticAnalysis"
        cmd = "java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphFSRun RankerWeka "+top+" "+ alg
        cmdLOG = "java -cp GraphFSRun RankerWeka "+top+" "+ alg
#        subprocess.call(cmd, shell=True)
        print time.strftime("%Y-%m-%d %H:%M") + " "+cmdLOG +"\n"

        print "\n Rec \n"
        for given in givenN:
            if given != "given_all":
#               cmd = "java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun given_5 RankerWeka 11 PCA &"
                cmd = "java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun "+given+" RankerWeka "+top+" "+alg+" &"
                cmdLOG = "java -cp GraphRecRun "+given+" RankerWeka "+top+" "+alg+" &"
                print time.strftime("%Y-%m-%d %H:%M") + " "+cmdLOG
#                subprocess.call(cmd, shell=True)
            else:
                cmd = "java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun "+given+" RankerWeka "+top+" "+alg
                cmdLOG = "java -cp GraphRecRun "+given+" RankerWeka "+top+" "+alg
                print time.strftime("%Y-%m-%d %H:%M") + " "+cmdLOG
#                subprocess.call(cmd, shell=True)

        print "\n Eval \n"
        for given in givenN:
            cmd = "java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphEvalRun "+given+" RankerWeka "+top+" "+alg
            cmdLOG = "java -cp GraphEvalRun "+given+" RankerWeka "+top+" "+alg
            print time.strftime("%Y-%m-%d %H:%M") + " "+cmdLOG

