#!/usr/bin/python

import modSperim

#mrmr                       
#InfoGainAttributeEval	         
#ReliefFAttributeEval	     17    

#ChiSquaredAttributeEval	
#GainRatioAttributeEval 	 
#PCA	                    17 30 50
#SVMAttributeEval                    

cmdThread="ps aux | grep \'java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun\' | grep -v \'color=auto\' | grep -v \'/bin/sh\' |wc -l"

param=6
allalg=[]
allalgWEKA=["PCA"]
#allalg=["ChiSquaredAttributeEval","GainRatioAttributeEval","SVMAttributeEval"]
topN=["50"]
givenN=["given_5","given_10","given_20","given_30","given_50","given_all"]


modSperim.sperim(allalg, allalgWEKA, topN, givenN, param, cmdThread)
