#!/usr/bin/env Rscript
args <- commandArgs(trailingOnly = TRUE)
sink(args[2])
temp = list.files(path = args[1], pattern="*.csv",full.names=TRUE)
for (j in 1:length(temp)) {
    mydata=read.csv(temp[j]) 
    print(temp[j])    
    print(mydata)
#    print(friedman.test(as.matrix(mydata)))
    print(friedman.test(as.matrix(mydata)))
}


library(car)
options(contrasts=c("contr.sum","contr.poly"))
mydata = read.csv("~/Scrivania/conf_17Features_given_all_5Top_F1.csv")
attach(mydata)
multimodel=lm(cbind(PageRank,MRMR,RankerWekaChiSquaredAttributeEval,RankerWekaGainRatioAttributeEval,RankerWekaSVMAttributeEval,RankerWekaInfoGainAttributeEval,RankerWekaPCA,RankerWekaReliefFAttributeEval) ~ 1)
Trials=factor(c("PageRank","MRMR","RankerWekaChiSquaredAttributeEval","RankerWekaGainRatioAttributeEval","RankerWekaSVMAttributeEval","RankerWekaInfoGainAttributeEval","RankerWekaPCA","RankerWekaReliefFAttributeEval"), ordered = F)
model1=Anova(multimodel,idata=data.frame(Trials),idesign=~Trials,type="III")
summary(model1,multivariate=F)

