#!/usr/bin/python

import statProp

dataset = ["lastfm"]
# dataset=["movielens","dbbooks"]

#allalg=["CFSubsetEval","PageRank","MRMR"]
#allalgWEKA=["ChiSquaredAttributeEval","GainRatioAttributeEval","SVMAttributeEval", "InfoGainAttributeEval","PCA","ReliefFAttributeEval"]
##topN=["10","17","30","50"]
metrics=["F1","Novelty","Diversity"]
givenN=["given_5","given_10","given_20","given_30","given_50","given_all"]

param=3
algBaseline=["UserKNN", "ItemKNN", "Random", "MostPopular", "BPRMF"]
allalg = ["PageRank"]
allalgWEKA=[]
topN = ["50"]
#topN=["10","30","50"]
#givenN=["given_5","given_all"]
#metrics=["F1"]

givenCSV=["given_5","given_20","given_all"]
valMetricsCSV=["5","10","20"]
best="PageRank"
topBest="50"

cmdThreadFS="ps aux | grep \'java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphFSRun\' | grep -v \'color=auto\' | grep -v \'/bin/sh\' |wc -l"

cmdThreadRec="ps aux | grep \'java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun\' | grep -v \'color=auto\' | grep -v \'/bin/sh\' |wc -l"

cmdThreadEval="ps aux | grep \'java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphEvalRun\' | grep -v \'color=auto\' | grep -v \'/bin/sh\' |wc -l"

cmdThreadBaseline="ps aux | grep \'java -cp lodrecsys.jar di.uniba.it.lodrecsys.baseline.Baseline\' | grep -v \'color=auto\' | grep -v \'/bin/sh\' |wc -l"

#CFSubsetEval
#mrmr 
#PageRank                      
#InfoGainAttributeEval	         
#ReliefFAttributeEval	         
#ChiSquaredAttributeEval	
#GainRatioAttributeEval 
#PCA	                    
#SVMAttributeEval  


statProp.extractPropertiesStat(dataset)
# downloadProp.extractProperties(dataset)

#modSperim.sperimRunner(dataset, allalg, allalgWEKA, topN, givenN, param, cmdThreadFS, cmdThreadRec, cmdThreadEval, metrics, best, topBest, givenCSV, valMetricsCSV, cmdThreadBaseline, algBaseline)
