#!/usr/bin/python

import modSperim

#allalg=["CFSubsetEval","PageRank","MRMR"]
#allalgWEKA=["ChiSquaredAttributeEval","GainRatioAttributeEval","SVMAttributeEval", "InfoGainAttributeEval","PCA","ReliefFAttributeEval"]
topN=["10","17","30","50"]
metrics=["F1","Novelty","Diversity"]
#givenN=["given_5","given_10","given_20","given_30","given_50","given_all"]

param=3
allalg=["CFSubsetEval"]
allalgWEKA=[] 
#topN=["17"]
givenN=["given_5","given_10","given_20","given_30","given_50","given_all"]
#metrics=["F1"]

best="PageRank"
topBest="50"

dire="./datasets/ml-100k/results/UserItemExpDBPedia/"

cmdThreadFS="ps aux | grep \'java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphFSRun\' | grep -v \'color=auto\' | grep -v \'/bin/sh\' |wc -l"

cmdThreadRec="ps aux | grep \'java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun\' | grep -v \'color=auto\' | grep -v \'/bin/sh\' |wc -l"

cmdThreadEval="ps aux | grep \'java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphEvalRun\' | grep -v \'color=auto\' | grep -v \'/bin/sh\' |wc -l"

#CFSubsetEval
#mrmr 
#PageRank                      
#InfoGainAttributeEval	         
#ReliefFAttributeEval	         
#ChiSquaredAttributeEval	
#GainRatioAttributeEval 
#PCA	                    
#SVMAttributeEval          

modSperim.sperim(allalg, allalgWEKA, topN, givenN, param, cmdThreadFS, cmdThreadRec, cmdThreadEval, metrics, best, topBest, dire)

