#!/usr/bin/python

import modSperim
import downloadProp

allalg=["CFSubsetEval","PageRank","MRMR"]
allalgWEKA=["ChiSquaredAttributeEval","GainRatioAttributeEval","SVMAttributeEval", "InfoGainAttributeEval","PCA","ReliefFAttributeEval"]
#topN=["10","17","30","50"]
metrics=["F1","Novelty","Diversity"]
givenN=["given_5","given_10","given_20","given_30","given_50","given_all"]

param=2
#allalg=["PageRank"]
#allalgWEKA=[] 
topN=["10","30","50"]
#givenN=["given_5"]
#metrics=["F1"]
nSplit="5"

givenCSV=["given_5","given_20","given_all"]
valMetricsCSV=["5","10","20"]
best="PageRank"
topBest="50"

dire="./datasets/ml-100k/results/UserItemExpDBPedia/"
dirProp="./datasets/ml-100k/stored_prop/"

cmdThreadFS="ps aux | grep \'java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphFSRun\' | grep -v \'color=auto\' | grep -v \'/bin/sh\' |wc -l"

cmdThreadRec="ps aux | grep \'java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphRecRun\' | grep -v \'color=auto\' | grep -v \'/bin/sh\' |wc -l"

cmdThreadEval="ps aux | grep \'java -cp lodrecsys.jar di.uniba.it.lodrecsys.graph.GraphEvalRun\' | grep -v \'color=auto\' | grep -v \'/bin/sh\' |wc -l"

#CFSubsetEval
#mrmr 
#PageRank                      
#InfoGainAttributeEval	         
#ReliefFAttributeEval	         
#ChiSquaredAttributeEval	
#GainRatioAttributeEval 
#PCA	                    
#SVMAttributeEval  

downloadProp.extractProperties(dirProp)        

modSperim.sperimRunner(allalg, allalgWEKA, topN, givenN, param, cmdThreadFS, cmdThreadRec, cmdThreadEval, metrics, nSplit, best, topBest, dire, givenCSV, valMetricsCSV)

