#!/usr/bin/env Rscript
 #read the dataset into an R variable using the read.csv(file) function
 dataOneWayRepeatedMeasures <- read.csv("~/Scrivania/conf_17Features_given_all_5Top_F1.csv")
 
 #display the data
 #notice the atypical column arrangement for repeated measures data
# dataOneWayRepeatedMeasures

 #prepare the repeated measures factor

 #step 1: define the levels
 #use c() to create a vector containing the number of levels within the repeated measures factor
 #create a vector numbering the levels for our three voting interest age groups
 ageLevels <- c(1, 2, 3, 4, 5, 6, 7, 8)

 #step 2: define the factor
 #use as.factor() to create a factor using the levels from step 1
 #convert the age levels into a factor
 ageFactor <- as.factor(ageLevels)

 #step 3: define the frame
 #use data.frame() to create a data frame using the factor from step 2
 #convert the age factor into a data frame
 ageFrame <- data.frame(ageFactor)

 #step 4: bind the columns
 #use cbind() to bind the levels of the factor from the original dataset
 #bind the age columns
 ageBind <- cbind(dataOneWayRepeatedMeasures$PageRank, dataOneWayRepeatedMeasures$MRMR, dataOneWayRepeatedMeasures$RankerWekaChiSquaredAttributeEval, dataOneWayRepeatedMeasures$RankerWekaGainRatioAttributeEval, dataOneWayRepeatedMeasures$RankerWekaSVMAttributeEval, dataOneWayRepeatedMeasures$RankerWekaInfoGainAttributeEval, dataOneWayRepeatedMeasures$RankerWekaPCA, dataOneWayRepeatedMeasures$RankerWekaReliefFAttributeEval)

 #step 5: define the model
 #use lm() to generate a linear model using the bound factor levels from step 4
 #generate a linear model using the bound age levels
 ageModel <- lm(ageBind ~ 1)

 #load the car package (install first, if necessary)
 library(car)
 #compose the Anova(mod, idata, idesign) function
 analysis <- Anova(ageModel, idata = ageFrame, idesign = ~ageFactor)

 #use summary(object) to visualize the results of the repeated measures ANOVA
 summary(analysis,multivariate=F)
